-- NELPAC submitted preorders, registrations, and reward claims cleanup
--
-- WARNING: THIS IS A DESTRUCTIVE DATA-CLEANUP SCRIPT.
-- Run it in the Supabase SQL Editor only after creating a database backup.
--
-- Permanently removes:
--   1. All reward claims and only their claim-owned collection codes,
--      discount vouchers,
--      and reward-merch allocation records.
--   2. All pre-registration and onsite submissions, delegates, supplements,
--      and manually recorded onsite participant rows.
--   3. All submitted merchandise preorder data: orders, order items, and
--      supplemental orders.
--   4. Notifications and audit rows directly associated with the removed data.
--
-- Preserves:
--   - Auth users, profiles, local churches, and church member records
--   - Every post and announcement
--   - Every event, including AYA and 1st AYCM, and event form configuration
--   - Every merchandise preorder post/form and its configuration
--   - All youth/member address and profile information
--   - Reward catalog items
--   - Evaluation reward history and evaluation-earned points
--   - Event/One Card redeem codes, including AYA2026
--   - One Card point ledger entries and current reward stock quantities
--   - Evaluation submissions and all unrelated application data
--
-- One Card points, point balances, and reward stock are intentionally
-- preserved. Deleting a reward claim does not reverse or delete any existing
-- point-ledger entry; the user's balance remains exactly as it was before this
-- cleanup. Reset points only through a separately reviewed points migration.

begin;

-- ============================================================
-- 1. Remove notifications generated by these features
-- ============================================================

delete from public.notifications
where type = 'reward_claim'
   or title in (
     'Additional pre-registration submitted',
     'Additional merch pre-order submitted'
   );

-- ============================================================
-- 2. Remove reward claims and all claim-owned records
-- ============================================================

-- These tables come from the rewards/vouchers migration. Conditional deletes
-- let this cleanup remain usable on a database where that migration has not
-- yet been installed.
do $$
begin
  if to_regclass('public.registration_discount_vouchers') is not null then
    execute 'delete from public.registration_discount_vouchers';
  end if;

  if to_regclass('public.reward_merch_allocations') is not null then
    execute 'delete from public.reward_merch_allocations';
  end if;
end
$$;

-- public.redeem_codes contains only collection codes owned by reward_claims.
-- Do NOT delete from public.one_card_redeem_codes or
-- public.one_card_redeem_code_claims: those tables contain event codes such as
-- AYA2026. Evaluation reward history is also intentionally untouched.
delete from public.redeem_codes;
delete from public.reward_claims;

-- ============================================================
-- 3. Preserve ordinary posts and announcements
-- ============================================================

-- Intentionally no DELETE against public.posts_or_announcements. Existing
-- announcements and event-related posts remain visible after this cleanup.

-- ============================================================
-- 4. Remove submitted event registration data
-- ============================================================

-- Supplemental tables use ON DELETE CASCADE, but clearing them explicitly
-- documents the complete cleanup and also avoids unnecessary cascade work.
do $$
begin
  if to_regclass('public.event_registration_supplements') is not null then
    execute 'delete from public.event_registration_supplements';
  end if;
end
$$;

delete from public.event_registration_delegates;
delete from public.event_registrations;

-- Admin-entered onsite participants are stored separately from onsite form
-- submissions. Remove those rows without touching their parent events.
do $$
begin
  if to_regclass('public.onsite_event_participants') is not null then
    execute 'delete from public.onsite_event_participants';
  end if;
end
$$;

-- Event form settings remain on public.events so admins can reopen the same
-- forms later without rebuilding their configuration.

-- ============================================================
-- 5. Remove only submitted merch preorder data
-- ============================================================

do $$
begin
  if to_regclass('public.merch_preorder_supplements') is not null then
    execute 'delete from public.merch_preorder_supplements';
  end if;
end
$$;

-- Deleting a shirt item normally recalculates its parent order. Submitted
-- orders reject that recalculation, so pause only this maintenance trigger.
alter table public.merch_shirt_order_items
  disable trigger sync_shirt_preorder_total_trigger;

delete from public.merch_shirt_order_items;
delete from public.merch_preorders;

alter table public.merch_shirt_order_items
  enable trigger sync_shirt_preorder_total_trigger;

-- Intentionally no DELETE against public.merch_preorder_forms. The admin's
-- merchandise posts/forms remain available for new preorder submissions.

-- ============================================================
-- 6. Remove matching audit-log records
-- ============================================================

delete from public.audit_logs
where table_name in (
  'reward_claims',
  'redeem_codes',
  'registration_discount_vouchers',
  'reward_merch_allocations',
  'event_registrations',
  'event_registration_delegates',
  'event_registration_supplements',
  'onsite_event_participants',
  'merch_preorders',
  'merch_shirt_order_items',
  'merch_preorder_supplements'
);

commit;

-- SQL removes database rows only. Delete uploaded files separately from these
-- Supabase Storage buckets if their old files must also be erased:
--   - registration-payment-proofs
--   - merch-payment-proofs
--
-- Suggested post-run checks:
-- select count(*) from public.reward_claims;
-- select count(*) from public.event_registrations;
-- select count(*) from public.merch_preorders;
-- select count(*) from public.one_card_points;
-- select count(*) from public.events;
-- select count(*) from public.merch_preorder_forms;
-- select code from public.one_card_redeem_codes where upper(code) = 'AYA2026';
-- select title from public.posts_or_announcements order by created_at;
-- select title from public.events order by event_date;
